# Basic information
title: Sota Minowa
position: PhD Student in Social Science
email: sota.minowa@caltech.edu

# Search engine optimization
keywords: sota minowa, minowa Sota, sotaminowa
description:
canonical: https://sota.minowa.github.io

# Links
cv_link: assets/files/cv_minowa.pdf

# Images
avatar: assets/img/avatar2.jpg
favicon: assets/img/favicon-75.png

# Files excluded from the generated website
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
